// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5O0BQMZVOPDu3nfFeyHjA9eCRA7L_Mwk',
    appId: '1:993540512823:web:a48ebfd4e4fed83d4d33b2',
    messagingSenderId: '993540512823',
    projectId: 'watch-out-aa14f',
    authDomain: 'watch-out-aa14f.firebaseapp.com',
    storageBucket: 'watch-out-aa14f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcwes7MT7W-uLJTpRY884Db4hGD0xy6WU',
    appId: '1:993540512823:android:18adf6d537395d024d33b2',
    messagingSenderId: '993540512823',
    projectId: 'watch-out-aa14f',
    storageBucket: 'watch-out-aa14f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5mbMs_WeGjq3yS8M6o_Mt0u2rYf-1ksE',
    appId: '1:993540512823:ios:6e88f0438dd9c5244d33b2',
    messagingSenderId: '993540512823',
    projectId: 'watch-out-aa14f',
    storageBucket: 'watch-out-aa14f.appspot.com',
    iosClientId: '993540512823-9mvrlgi13ge6jmaectsfn54riqii8es8.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5mbMs_WeGjq3yS8M6o_Mt0u2rYf-1ksE',
    appId: '1:993540512823:ios:6e88f0438dd9c5244d33b2',
    messagingSenderId: '993540512823',
    projectId: 'watch-out-aa14f',
    storageBucket: 'watch-out-aa14f.appspot.com',
    iosClientId: '993540512823-9mvrlgi13ge6jmaectsfn54riqii8es8.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchOut',
  );
}
